### ISSUE TITLE
About the ids

### ISSUE THREAD

**Issue by hshsilver** [s1cp/nxshot#54]
Hello, 
Could you please tell me whether there is a rule for game names to convert into the id such as  "F1C11A22FAEE3B82F21B330E1B786A39" is "The Legend of Zelda™ - Breath of the Wild (CHN EUR JPN KOR USA)"?
BTW, the website SwitchBrew has a different length ID number. How did you convert it?

**Comment by dmynerd78** [comment]
It's somewhat complicated but the code can be found [here](https://github.com/s1cp/nxshot/blob/master/nxshot.py#L79-L85) (sourced from Issue #42).

If you can't get that working you can always edit the gameids.json file directly by adding `"screenshot_id": "Game Title Here",` to it

**Comment by hshsilver** [comment]
Did you mean
1. the final code F1C11A22FAEE3B82F21B330E1B786A39 is converted from titleIDs according to the algorithm you mentioned. 
2. the titleIDs are fixed and randomly set by Nintendo or Game developers but not converted from just the names.

**Comment by dmynerd78** [comment]
Sorry forgot to check my email. Basically `F1C11A22FAEE3B82F21B330E1B786A39` is the decrypted form of a game's titleID. That algorithm takes the encrypted form of a titleID (for BotW it's `01007EF00011E000`) and it spits out the decrypted form (the version that is embedded within the screenshot file). TitleIDs are fixed by Nintendo/Game Developer.
